default: &default
  adapter: postgresql
  encoding: unicode
  username: mbr_db_admin
  password: <%= ENV['MINI_BATTLE_ROYALE_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mini_battle_royale_development

test:
  <<: *default
  database: mini_battle_royale_test

production:
  <<: *default
  database: mini_battle_royale_production

staging:
  <<: *default
  database: mini_battle_royale_staging
